### ISSUE TITLE
downloading folder results in exception

### ISSUE THREAD

**Issue by stefanseefeld** [anancarv/python-artifactory#63]
Calling ```art.artifacts.download('some-directory/', 'some-path')```

I expected the "some-directory/" folder to be downloaded either as "some-path/", or into "some-path/".
Instead, I'm receiving this stack-trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/.local/lib/python3.6/site-packages/pyartifactory/objects.py", line 810, in download
    with open(local_file_full_path, "wb") as file:
IsADirectoryError: [Errno 21] Is a directory: 'some-path/'
```
This seems wrong. Either I have called the `download` method with invalid arguments, in which case I would expect an exception telling me exactly that, or this is supposed to work but due to some bug it doesn't.

(Note that I also tried to figure out how to up- and download directories recursively using `curl` following the `jfrog` online docs, but couldn't get things to work. So it isn't entirely clear to me whether recursive downloads and uploads are supposed to work or whether I have to write my own wrapper API to recurse into the directory and up-/download files individually.)

I'm using artifactory 1.7.2 with Python 3.6.

Thanks !

**Comment by anancarv** [comment]
Hi @stefanseefeld 
The download method is based on the [Retrieve artifact endpoint](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveArtifact) from the artifactory API which retrieves an artifact from a specified destination. As you can see on the example in the README, the function expects the absolute path of the artifact, not the folder within in it resides.
```
artifact = art.artifacts.download("my-artifactory-repository/my/new/artifact/file.txt", "Desktop/my/local/directory")
```

In the trace you sent. It is written that `some-path` is a directory path instead of an actual `artifact path`
```
IsADirectoryError: [Errno 21] Is a directory: 'some-path/'
```

Downloading directories recursively is not yet implemented by this library and I'm not sure it's even implemented by Jfrog.  However, you can use the [Retrieve Folder or Repository Archive](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveFolderorRepositoryArchive) that retrieves an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts that reside under the specified path (folder or repository root). It requires `Enable Folder Download` to be set.

Let me know if you have any questions
Cheers

**Comment by stefanseefeld** [comment]
Hi @anancarv , thank you for your prompt reply !
I have just looked at the code in `pyartifactory.objects.ArtifactoryArtifact.download()`. The first argument is the name of the artifact to be downloaded, the second argument is the name of a local directory into which to download it. Line 804 makes sure the local directory (and its parents) exist, so this is why in my case the directory was created. The real problem is in line 801:
```local_filename = artifact_path.split("/")[-1]```
In my case, that yields '', because my artifact name ends with '/' (i.e., is a directory). This means `local_file_full_path` will refer to an existing directory, rather than a not-yet-existing file-within-a-directory, and thus line 810 will trigger the exception I reported.

It thus turns out the expectation is that the first argument to the `download()` method is expected to refer to a file, not a directory, which the error should explain.

OK, so I now understand that downloading and uploading directories isn't working - yet, so I will write my own wrapper to support directory navigation (perhaps akin to `os.listdir()`).
Just out of curiosity: would you be interested in such a contribution to `pyartifacts` ? (I'm also writing a command-line tool akin to the Jfrog CLI, but supporting the above functionality.
(I'm working with a couple of "generic" artifact repositories which we use to store data files, and I would like to be able to access them from within Python (e.g. jupyter notebooks).

Thanks !

**Comment by anancarv** [comment]
You're welcome 😉. 
Sure, it would be great to have this functionality in `pyartifactory`, I'm looking forward your contribution.
